---
build-job:
  stage: build
  script:
    - echo "Building project..."
    - npm --v
    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mocha test

curl-test-job:
  stage: test
  script:
    - echo "Running CURL tests..."
    - chmod +x ./test/curl/*.sh
    - ./test/curl/curl_tests.sh

deliver-job:
  stage: deploy
  script:
    - echo "Deploying to class server..."
    - echo "$PRIVATE_KEY" > ./my_private_key
    - chmod 400 ./my_private_key
    - ssh -i ./my_private_key mio755@10.100.201.3 "cd ~/cs4783-assignment1; git pull; pm2 reload all"
    - rm ./my_private_key
...
