---
build-job:
  stage: build
  script:
    - echo "Building project..."
#    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
#    - mocha test

curl-test-job:
  stage: test
  script:
    - echo "Deploying to class server..."
#    - echo "$PRIVATE_KEY" > ./my_private_key
#    - chmod 400 ./my_private_key
#    - ssh -i ./my_private_key fru574@10.100.201.3 "cd ~/cs4783-spring2021; git pull; pm2 reload all"
#    - rm ./my_private_key
#    - sleep 10
#    - sleep 20
    - echo "Running CURL tests..."
#    - chmod +x ./src/test/curl/*.sh
#    - ./src/test/curl/curltest.sh

deliver-job:
  stage: deploy
  script:
    - echo "delivered. where's my money?"
...
