apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jaked\Desktop\cs4783-assignment1\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mio755-db
  name: mio755-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mio755-db
status:
  loadBalancer: {}
